// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6eS_owFYXjyV1mzTkBmCNnfK859cIguI',
    appId: '1:382670022014:web:1edb7864ab2d83bf777f2f',
    messagingSenderId: '382670022014',
    projectId: 'fundahub-f13b4',
    authDomain: 'fundahub-f13b4.firebaseapp.com',
    storageBucket: 'fundahub-f13b4.firebasestorage.app',
    measurementId: 'G-EM32N3KE8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiN6ciyoW6xKvImAlQqe4n5ytQ0fEKwXU',
    appId: '1:382670022014:android:b667ab00552d9396777f2f',
    messagingSenderId: '382670022014',
    projectId: 'fundahub-f13b4',
    storageBucket: 'fundahub-f13b4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDdyK9oSY4RI7MQyfn6LGneAVn9xIaABI',
    appId: '1:382670022014:ios:1f90d6ba8fb30bad777f2f',
    messagingSenderId: '382670022014',
    projectId: 'fundahub-f13b4',
    storageBucket: 'fundahub-f13b4.firebasestorage.app',
    androidClientId:
        '382670022014-odm3foctqchhrgqsfhqvup71oo08quk9.apps.googleusercontent.com',
    iosClientId:
        '382670022014-pojv4e9d2qdh161hs2mna6prr42g5cuk.apps.googleusercontent.com',
    iosBundleId: 'com.fundahub.fundahub',
  );
}
